/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Global;

import Interfaces.InterfaceProgressController;
import java.awt.Cursor;
import java.awt.EventQueue;
import javax.swing.JDialog;

/**
 *
 * @author komputer1
 */
public class ProgressDialog extends javax.swing.JFrame implements InterfaceProgressController{
    private Boolean stop;

    /**
     * Creates new form ProgressDialog
     */
    public ProgressDialog() {
        initComponents();
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    }
    
    @Override
    public void run(){
        EventQueue.invokeLater(() -> {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            jProgressBar1.setValue(0);
            setVisible(true);
            stop = false;
        });
    }
    
    @Override
    public void setProgress(int i){
        EventQueue.invokeLater(() -> {
            jProgressBar1.setValue(i);
        });
    }
    
    @Override
    public void setMax(int max){
        EventQueue.invokeLater(() -> {
            jProgressBar1.setMaximum(max);
        });
    }
    
    @Override
    public boolean getStop(){
        return stop;
    }
    
    @Override
    public void end(){
        EventQueue.invokeLater(() -> {
            setVisible(false);
            this.setCursor(Cursor.getDefaultCursor());
        });
    }
    
    @Override
    public void setText(String text) {
        EventQueue.invokeLater(() -> {
            jLabel1.setText(text);
        });        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 200));
        getContentPane().setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        jProgressBar1.setValue(50);
        jProgressBar1.setMinimumSize(new java.awt.Dimension(146, 4));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(400, 10));
        getContentPane().add(jProgressBar1);

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        stop = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
