/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.BasicView;

import Other.DateLabelFormatter;
import java.awt.BorderLayout;
import java.util.Properties;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Marek
 */
public class FilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterPanel
     */
    public FilterPanel() {
        initComponents();
        JDatePickerImpl datePickerOd = null;
        JDatePickerImpl datePickerDo = null;
        UtilDateModel modelOd = new UtilDateModel();
        UtilDateModel modelDo = new UtilDateModel();
        Properties p = new Properties();
        
        p.put("text.today", "Today");
        JDatePanelImpl datePanelOd = new JDatePanelImpl(modelOd, p);
        JDatePanelImpl datePanelDo = new JDatePanelImpl(modelDo, p);
        datePickerOd = new JDatePickerImpl(datePanelOd, new DateLabelFormatter());
        datePickerDo = new JDatePickerImpl(datePanelDo, new DateLabelFormatter());
        pnlOd.add(datePickerOd,BorderLayout.CENTER);
        pnlDo.add(datePickerDo,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOd = new javax.swing.JLabel();
        lblDo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlOd = new javax.swing.JPanel();
        pnlDo = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        setPreferredSize(new java.awt.Dimension(142, 78));
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        lblOd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOd.setText("Od:");
        jPanel1.add(lblOd);

        lblDo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDo.setText("Do:");
        jPanel1.add(lblDo);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        pnlOd.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pnlOd);

        pnlDo.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pnlDo);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDo;
    private javax.swing.JLabel lblOd;
    private javax.swing.JPanel pnlDo;
    private javax.swing.JPanel pnlOd;
    // End of variables declaration//GEN-END:variables
}
