/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.BasicView;

import Interfaces.MyWindowInterface;
import Interfaces.MyPanelInterface;
import java.awt.Window;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author Marek
 */
public class MainWindow extends javax.swing.JFrame implements MyWindowInterface{
    private MyWindowManager myWindowManager = null;
    private Window parent;
    
    public MainWindow(MyPanelInterface parent, KonfigView konfigView, String title, MyPanelInterface panel) {
        initComponents();        
        
        myWindowManager = new MyWindowManager();
        myWindowManager.create(this, konfigView, title, panel);
        if (parent != null){
            this.parent = getOlderParent ((JPanel) parent);
        }
        else{
            this.parent = null;
        }
        init();
    }
    
    private Window getOlderParent(JComponent panel){
        if (!(panel.getParent() instanceof Window)){
            return getOlderParent((JComponent) panel.getParent());
        }
        else{
            return (Window) panel.getParent();
        }
    }
    
    @Override
    public void init(){
        setDefaultCloseOperation(myWindowManager.getKonfigView().getDefaultOperationOnClose());
    }

    @Override
    public void setVisible(boolean b) {
        if (b == true){
            pack();
            setLocationRelativeTo(null);
            setExtendedState(myWindowManager.getKonfigView().getExtendedState());
            myWindowManager.setResizeListener(this);
            myWindowManager.getWorkingPanel().loadPreferences();
        }
        else{
            myWindowManager.getWorkingPanel().savePreferences();
        }
        if (parent != null){parent.setVisible(!b);}
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public <E> void unpackWindow(List<E> objectList) {
        myWindowManager.unpackWindow(objectList);
    }

    @Override
    public <E> void unpackWindow(E object) {
        myWindowManager.unpackWindow(object);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(null, null, "", null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
