/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.BasicView;

import Interfaces.MyPanelInterface;
import java.io.Serializable;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Marek
 */
public class TitlePanel extends BasePanel{   
    public TitlePanel(String title) {
        super();
        initComponents();
        if (title != ""){
            jLabel1.setText("  " + title + "  ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlWorkingPanel = new javax.swing.JPanel();

        setName(""); // NOI18N
        setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pnlWorkingPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlWorkingPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlWorkingPanel.setLayout(new java.awt.BorderLayout());
        add(pnlWorkingPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlWorkingPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getWorkingPanel() {
        return pnlWorkingPanel;
    }
}
