/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.BasicView;

import Interfaces.MyPanelInterface;
import java.awt.event.KeyEvent;
import java.io.Serializable;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Marek
 */
public class TitlePanel extends BasePanel{   
    public TitlePanel(String title) {
        super(null);
        initComponents();
        if (title != ""){
            jLabel1.setText("  " + title + "  ");
        }
        btnOk.setMnemonic(KeyEvent.VK_O);
        btnCancel.setMnemonic(KeyEvent.VK_A);
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlBtnPanel = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlWorkingPanel = new javax.swing.JPanel();

        setName(""); // NOI18N
        setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pnlBtnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlBtnPanel.add(btnOk);

        btnCancel.setText("Anuluj");
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlBtnPanel.add(btnCancel);

        add(pnlBtnPanel, java.awt.BorderLayout.SOUTH);

        pnlWorkingPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlWorkingPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlWorkingPanel.setLayout(new java.awt.BorderLayout());
        add(pnlWorkingPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBtnPanel;
    private javax.swing.JPanel pnlWorkingPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getWorkingPanel() {
        return pnlWorkingPanel;
    }

    public JPanel getPnlBtnPanel() {
        return pnlBtnPanel;
    }
}
