/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entities.PotrawyWDniu;
import View.BasicView.BasePanel;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.SwingConstants.RIGHT;

/**
 *
 * @author Marek
 */
public class DaysPanel extends BasePanel {
    List<PotrawyWDniu> listOfDays = null;
    List<Integer> forHowManyDays = null;
    List<JTextField> listOfTextFileds = null;
    
    public DaysPanel() {
        super(null);
        initComponents();
    }

    @Override
    public void pack() {
        for (JTextField edt : listOfTextFileds) {
            forHowManyDays.add((Integer) Global.GlobalFun.bind(edt, Integer.class));
        }
    }

    @Override
    public <E> void unpack(List<E> objectList) {
        listOfDays = (List<PotrawyWDniu>) objectList.get(0);
        forHowManyDays = (List<Integer>) objectList.get(1);
        listOfTextFileds = new ArrayList<>();
        for (int i = 0; i < listOfDays.size(); i++) {
            addRow(listOfDays.get(i).getNazwa());
        }
    }
    
    private void addRow(String dietTitle){
        increaseRows((GridLayout) pnlDietName.getLayout());
        increaseRows((GridLayout) pnlDaysNumber.getLayout());
        
        JTextField edt = new JTextField("1");
        edt.setHorizontalAlignment(RIGHT);
        if (dietTitle == null){
            dietTitle = "Dieta bez nazwy";    
        }
        pnlDietName.add(new JLabel(dietTitle + ":"));
        pnlDaysNumber.add(edt);
        listOfTextFileds.add(edt);
    }
    
    private void increaseRows(GridLayout layout){
        layout.setRows(layout.getRows() + 1);        
    }

    @Override
    public Boolean execute() {
        boolean res = true;
        for (JTextField edt : listOfTextFileds) {
            try {
                Integer number = Integer.parseInt(edt.getText());
                if (number < 1){
                    res = false;
                    break;
                }
            } catch (NumberFormatException nfe) {
                res = false;
                break;
            }               
        }
        if (res == false){
            JOptionPane.showMessageDialog(this, "Pojedyncza dieta jest generowana co najmniej na 1 dzień. Popraw ilość dni.", "Błąd", JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        else{
            return super.execute();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDietName = new javax.swing.JPanel();
        pnlDaysNumber = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout(5, 5));

        pnlDietName.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        add(pnlDietName, java.awt.BorderLayout.WEST);

        pnlDaysNumber.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        add(pnlDaysNumber, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDaysNumber;
    private javax.swing.JPanel pnlDietName;
    // End of variables declaration//GEN-END:variables
}
