/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Other.KonfigView;
import Other.MyPanelInterface;
import Other.Produkty;
import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Marek
 */
public class ListaProduktowView extends javax.swing.JPanel implements MyPanelInterface{
    private List<Produkty> productsList;

    @Override
    public <E> void unpack(E object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public <E> void unpack(List<E> objectList){
        String[] titleList = null;

        for (E product : objectList){
            productsList.add((Produkty) product);
        } 
        
        updateTable();
    }
    
    private void updateTable(){
        Field[] fields = Produkty.class.getDeclaredFields();
        fields = Arrays.copyOfRange(fields, 1, fields.length);
        
        
        while(jTable1.getColumnCount() < fields.length){
            TableColumn tblcol = new TableColumn();
            jTable1.addColumn(new TableColumn());
        }
        
        for (int i = 0; i < fields.length; i++) {
            jTable1.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(fields[i].getName());
        }
        
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        for (int j = 0; j < productsList.size(); j++) {
            String[] row = new String[fields.length];
            for (int i = 0; i < fields.length; i++) {
                try {
                    Boolean oldAccess;
                    oldAccess =  fields[i].canAccess(productsList.get(j));
                    fields[i].setAccessible(true);
                    row[i] = fields[i].get(productsList.get(j)).toString();
                    fields[i].setAccessible(oldAccess);
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(ListaProduktowView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ListaProduktowView.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            ((DefaultTableModel) jTable1.getModel()).addRow(row);
        }        
    }

    @Override
    public void pack() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private KonfigView konfigView;
    
    @Override
    public Boolean execute() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates. 
    }
    
    @Override
    public Boolean init(KonfigView konfigView) {
        this.konfigView = new KonfigView(konfigView);
        return true;
    }

    @Override
    public KonfigView getKonfigView() {
        return konfigView;
    }

    /**
     * Creates new form ListaProduktowView
     */
    public ListaProduktowView() {
        initComponents();
        productsList = new ArrayList<Produkty>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(776, 521));
        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 300));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable1.getSelectedRow() > -1){
            konfigView.setDefaultOperationOnClose(WindowConstants.HIDE_ON_CLOSE);
            konfigView.setExtendedState(JFrame.NORMAL);
            
            MainDialog mainWindow = new MainDialog(null, true, konfigView, "Produkt", new ProduktView());
            mainWindow.unpackWindow(productsList.get(jTable1.getSelectedRow()));
            
            mainWindow.setVisible(true);
            
            updateTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        konfigView.setDefaultOperationOnClose(WindowConstants.HIDE_ON_CLOSE);
        konfigView.setExtendedState(JFrame.NORMAL);
        
        MainDialog mainWindow = new MainDialog(null, true, konfigView, "Produkt", new ProduktView());
        mainWindow.unpackWindow(new Produkty());
        
        mainWindow.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
