/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Global.GlobalFun;
import View.BasicView.KonfigView;
import Interfaces.MyPanelInterface;
import Global.ORMManager;
import View.BasicView.BasePanel;
import java.io.Serializable;
import java.util.List;
import java.util.Properties;
import org.hibernate.cfg.Configuration;

/**
 *
 * @author Marek
 */
public class LoginPanel extends BasePanel{
    private ORMManager ormManager;
    private Properties properties;
    
    public LoginPanel(){
        super();
        initComponents();
    }
    
    @Override
    public <E> void unpack(E object) {
        super.unpack(object);
        properties = (Properties) object;
        GlobalFun.bind(properties.getProperty("hibernate.connection.username"), edtUsername);
        GlobalFun.bind(properties.getProperty("hibernate.connection.password"), edtPassword);
        GlobalFun.bind(properties.getProperty("hibernate.connection.url"), edtAresDB);
    }

    @Override
    public void pack() {
        properties.setProperty("hibernate.connection.username", (String) GlobalFun.bind(edtUsername, String.class));
        properties.setProperty("hibernate.connection.password", new String(edtPassword.getPassword()));
        properties.setProperty("hibernate.connection.url", (String) GlobalFun.bind(edtAresDB, String.class));
    }
    
    @Override
    public Boolean execute() {
        super.execute();
        ormManager = ORMManager.getOrmManager();
        return ormManager.connect(properties);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtUsername = new javax.swing.JTextField();
        edtPassword = new javax.swing.JPasswordField();
        edtAresDB = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblAdresDB = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        edtUsername.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(edtUsername);

        edtPassword.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(edtPassword);

        edtAresDB.setText("jdbc:firebirdsql://localhost:3050/C:/Users/Marek/Documents/GitHub/NourishmentApp/NourishmentApp/Nourishment/DB/NOURISHMENT.FDB");
        edtAresDB.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(edtAresDB);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Użytkownik");
        jPanel2.add(lblUsername);

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Hasło");
        lblPassword.setRequestFocusEnabled(false);
        jPanel2.add(lblPassword);

        lblAdresDB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdresDB.setText("Adres bazy danych");
        lblAdresDB.setRequestFocusEnabled(false);
        jPanel2.add(lblAdresDB);

        add(jPanel2, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtAresDB;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdresDB;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
