/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entities.Potrawy;
import Entities.Produkty;
import Entities.ProduktyWPotrawie;
import Global.GlobalFun;
import Interfaces.MyPanelInterface;
import View.BasicView.BaseListPanel;
import View.BasicView.MainDialog;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Marek
 */
public class PotrawyListView extends BaseListPanel {
    BaseListPanel pnlPotrawyList = null;
    BaseListPanel pnlProduktyList = null;

    /**
     * Creates new form PotrawyListView
     */
    public PotrawyListView(MyPanelInterface detailPanel, String detailPanelTitle, Class detailEntityClass) {
        super(detailPanel, detailPanelTitle, detailEntityClass);
        JPanel pnlPotrawy = new JPanel();
        JPanel pnlPotrawyButtons = new JPanel();
        JButton btnPotrawyOk = new JButton();
        
        pnlPotrawy.setLayout(new BorderLayout());
        pnlPotrawyButtons.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        pnlPotrawy.setBorder(BorderFactory.createRaisedBevelBorder());
        pnlPotrawyButtons.add(btnPotrawyOk);
        pnlPotrawy.add(pnlPotrawyButtons, BorderLayout.SOUTH);
        pnlPotrawyList = new BaseListPanel(new PotrawyView(), "Potrawa", Potrawy.class);
        pnlPotrawy.add(pnlPotrawyList, BorderLayout.CENTER);
        pnlPotrawy.setPreferredSize(new Dimension(450, 450));
        
        JPanel pnlProdukty = new JPanel();
        JPanel pnlProduktyButtons = new JPanel();
        JButton btnProduktyOk = new JButton();
        
        pnlProdukty.setLayout(new BorderLayout());
        pnlProduktyButtons.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        pnlProdukty.setBorder(BorderFactory.createRaisedBevelBorder());
        pnlProduktyButtons.add(btnProduktyOk);
        pnlProdukty.add(pnlProduktyButtons, BorderLayout.SOUTH);
        pnlProduktyList = new BaseListPanel(new ProduktView(), "Produkt", Produkty.class);
        pnlProdukty.add(pnlProduktyList, BorderLayout.CENTER);
        pnlProdukty.setPreferredSize(new Dimension(450, 450));
        
        this.add(pnlProdukty,BorderLayout.WEST);
        this.add(pnlPotrawy,BorderLayout.EAST);
        this.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height));
        pack();
        
        btnAdd.setText("<<");
        btnEdit.setText(">>");
    }

    @Override
    public void addObject(MyPanelInterface detailPanel, String title, Class objectType) {
        if (pnlPotrawyList.getCurrentObject() != null){
            ProduktyWPotrawie prodWPotr = new ProduktyWPotrawie();
            prodWPotr.setIdProduktu(pnlProduktyList.getCurrentObject());
            prodWPotr.setIdPotrawy(pnlPotrawyList.getCurrentObject());
            MainDialog wagaProduktuDialog = new MainDialog(null, true, konfigView, "Produkt w potrawie", new WagaProduktuPanel());
            wagaProduktuDialog.getMyWindowManager().unpackWindow(prodWPotr);
            wagaProduktuDialog.setVisible(true);
            if (wagaProduktuDialog.getResult()){
                if (((Potrawy) pnlPotrawyList.getCurrentObject()).getProduktyWPotrawieCollection() == null){
                    ((Potrawy) pnlPotrawyList.getCurrentObject()).setProduktyWPotrawieCollection(new ArrayList<ProduktyWPotrawie>() );
                }
                ((Potrawy) pnlPotrawyList.getCurrentObject()).getProduktyWPotrawieCollection().add(prodWPotr);
                //prodWPotrList = GlobalFun.toList(((Potrawy) pnlPotrawyList.getCurrentObject()).getProduktyWPotrawieCollection());
                newOrEditedObjectList.add((Potrawy) pnlPotrawyList.getCurrentObject());
            }
            updateView();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
