/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Other.KonfigView;
import Other.MyPanelInterface;

/**
 *
 * @author Marek
 */
public class ProduktView extends javax.swing.JPanel implements MyPanelInterface{
    private KonfigView konfigView;
    
    @Override
    public KonfigView getKonfigView() {
        return konfigView;
    }

    @Override
    public Boolean init(KonfigView konfigView) {
        return true;
    }

    /**
     * Creates new form ProduktView
     */
    public ProduktView(KonfigView konfigView) {
        initComponents();
        this.konfigView = new KonfigView(konfigView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(112, 56));

        jLabel1.setText("jLabel1");
        add(jLabel1);

        jTextField1.setText("jTextField1");
        add(jTextField1);

        jLabel2.setText("jLabel2");
        add(jLabel2);

        jTextField2.setText("jTextField2");
        add(jTextField2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
