/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entities.ProduktyWPotrawie;
import Global.GlobalFun;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Marek
 */
public class WagaProduktuWPotrawiePanel extends WagaProduktuPanel {
    ProduktyWPotrawie prodWPotr = null;

    /**
     * Creates new form WagaProduktuWPotrawiePanel
     */
    public WagaProduktuWPotrawiePanel() {
        super();
    }

    @Override
    public void pack() {
        prodWPotr.setIloscWG((Double) GlobalFun.bind(edtWagaProdruktu, Double.class));
    }

    @Override
    public <E> void unpack(E object) {
        prodWPotr = (ProduktyWPotrawie) object;
        List<Double> list = new ArrayList<>();
        list.add(prodWPotr.getIloscWG());
        list.add(prodWPotr.getIdProduktu().getWagaJednostki());
        super.unpack(list);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
